@include('include.header') <div id="post-header" class="page-header"> <div class="page-header-bg" style="background-image: url({{asset('./img/tagheuer3.jpg')}});" data-stellar-backgroundratio="0.5"></div> <div class="container"> <div class="row"> <div class="col-md-10"> <div class="post-category"> <a href="category.html">{{$title}}</a> </div> 

 
<h1>Mel ut impetus suscipit tincidunt. Cum id ullum laboramus persequeris.</h1> <ul class="post-meta"> <li><a href="author.html">John Doe</a></li> <li>{{$tag->created_at->toFormattedDateString()}}</li> <li><i class="fa fa-comments"></i> 3</li> <li><i class="fa fa-eye"></i> 807</li> </ul> </div> </div> </div> </div> <div class="section"> <div class="container"> <div class="row"> <div class="col-md-8"> <div class="post post-row"> <div class="post-body"> <div class="post-category">   </div> <ul class="post-meta"> <li><a href="author.html">Tag: {{$tag->tag}}</a></li> </ul> </div> </div> @foreach ($tag->posts as $post) <div class="post post-row"> <a class="post-img" href="{{route('post.show', ['slug' => $post>slug])}}"><img src="{{$post->featrued}}" alt=""></a> <div class="post-body"> <div class="post-category">   <a href="{{route('post.show', ['slug' => $post->slug])}}">{{$post>title}}</a> </div> <h3 class="post-title"><a href="{{route('post.show', ['slug' => $post->slug])}}">{{$post->updated_at>toFormattedDateString()}}</a></h3> <ul class="post-meta"> <li><a href="author.html">John Doe</a></li> <li>{{$post->created_at->toFormattedDateString()}}</li> </ul> <p>{!!$post->content!!}</p> </div> </div> @endforeach 
 
<br> <div class="section-row loadmore text-center"> <a href="#" class="primary-button">Load More</a> </div> </div> <div class="col-md-4"> <div class="aside-widget"> <div class="section-title"> <h2 class="title">Social Media</h2> </div> <div class="social-widget"> <ul> <li> <a href="#" class="social-facebook"> 

 
<i class="fa fa-facebook"></i> <span>21.2K<br>Followers</span> </a> </li> <li> <a href="#" class="social-twitter"> <i class="fa fa-twitter"></i> <span>10.2K<br>Followers</span> </a> </li> <li> <a href="#" class="social-google-plus"> <i class="fa fa-google-plus"></i> <span>5K<br>Followers</span> </a> </li> </ul> </div> </div> <div class="aside-widget"> <div class="section-title"> <h2 class="title">Categories</h2> </div> <div class="category-widget"> <ul> <li><a href="#">Lifestyle <span>451</span></a></li> <li><a href="#">Fashion <span>230</span></a></li> <li><a href="#">Technology <span>40</span></a></li> <li><a href="#">Travel <span>38</span></a></li> <li><a href="#">Health <span>24</span></a></li> </ul> </div> </div> <div class="aside-widget"> <div class="section-title"> <h2 class="title">Newsletter</h2> </div> <div class="newsletter-widget"> <form> <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium.</p> <input class="input" name="newsletter" placeholder="Enter Your Email"> <button class="primary-button">Subscribe</button> </form> </div> </div> </div> </div> </div> </div> <footer id="footer"> <div class="container"> <div class="row"> <div class="col-md-3"> <div class="footer-widget"> <div class="footer-logo"> <a href="index.html" class="logo"><img src="./img/logo-alt.png" alt=""></a> </div> <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium. Nisl purus in mollis nunc sed. Nunc non blandit massa enim nec.</p> 

 
<ul class="contact-social"> <li><a href="#" class="social-facebook"><i class="fa fafacebook"></i></a></li> <li><a href="#" class="social-twitter"><i class="fa fatwitter"></i></a></li> <li><a href="#" class="social-google-plus"><i class="fa fa-googleplus"></i></a></li> <li><a href="#" class="social-instagram"><i class="fa fainstagram"></i></a></li> </ul> </div> </div> <div class="col-md-3"> <div class="footer-widget"> <h3 class="footer-title">Categories</h3> <div class="category-widget"> <ul> <li><a href="#">Lifestyle <span>451</span></a></li> <li><a href="#">Fashion <span>230</span></a></li> <li><a href="#">Technology <span>40</span></a></li> <li><a href="#">Travel <span>38</span></a></li> <li><a href="#">Health <span>24</span></a></li> </ul> </div> </div> </div> <div class="col-md-3"> <div class="footer-widget"> <h3 class="footer-title">Tags</h3> <div class="tags-widget"> <ul> <li><a href="#">Social</a></li> <li><a href="#">Lifestyle</a></li> <li><a href="#">Blog</a></li> <li><a href="#">Travel</a></li> <li><a href="#">Technology</a></li> <li><a href="#">Fashion</a></li> <li><a href="#">Life</a></li> <li><a href="#">News</a></li> <li><a href="#">Magazine</a></li> <li><a href="#">Food</a></li> <li><a href="#">Health</a></li> </ul> </div> </div> </div> <div class="col-md-3"> <div class="footer-widget"> <h3 class="footer-title">Newsletter</h3> <div class="newsletter-widget"> <form> <p>Nec feugiat nisl pretium fusce id velit ut tortor pretium.</p> <input class="input" name="newsletter" placeholder="Enter Your Email"> <button class="primary-button">Subscribe</button> </form> </div> </div> </div> </div> <div class="footer-bottom row"> 
  
 
<div class="col-md-6 col-md-push-6"> <ul class="footer-nav"> <li><a href="index.html">Home</a></li> <li><a href="about.html">About Us</a></li> <li><a href="contact.html">Contacts</a></li> <li><a href="#">Advertise</a></li> <li><a href="#">Privacy</a></li> </ul> </div> <div class="col-md-6 col-md-pull-6"> <div class="footer-copyright"> Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">RahmaAltaee</a> </div> </div> </div> </div> </footer> <script src="js/jquery.min.js"></script> <script src="js/bootstrap.min.js"></script> <script src="js/jquery.stellar.min.js"></script> <script src="js/main.js"></script> </body> </html> 